### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by tobiasfielitz** [ashiina/lambda-local#118]
`lambda-local -l lambda.js -h screenshot -e local/event.json`

```
info: START RequestId: dc9d838a-d402-c4a8-1c25-75bb4659ce1a
error:  TypeError: Cannot read property 'indexOf' of undefined
    at Object.<anonymous> (/Users/ninja/projects/redmarker/lambda-js/src/s3.js:9:57)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ninja/projects/redmarker/lambda-js/lambda.js:5:12)
    at Module._compile (module.js:569:30)
```

I am able to invoke the function on AWS.

**Comment by gpotter2** [comment]
Hi,
Could you provide the code that crashes ?
Thanks

**Comment by tobiasfielitz** [comment]
`process.env.AWS_LAMBDA_FUNCTION_NAME.indexOf('production')`

**Comment by gpotter2** [comment]
Thanks a lot for reporting !

This is indeed a bug, as the provided context should contain all env vars :)

You might use the `-E` arg to add custom env vars to the context :)

**Comment by gpotter2** [comment]
Has been fixed in latest online dev version:
https://github.com/ashiina/lambda-local/archive/develop.zip

Thanks a lot for reporting !
