### ISSUE TITLE
Catch timeout error

### ISSUE THREAD

**Issue by tlovett1** [ashiina/lambda-local#131]
On timeout, lambda-local crashes. How can I catch this error?

**Comment by gpotter2** [comment]
Hi !
Sorry for the very late answer.

You can catch the error using its type, located in `utils.TimeoutError`

See https://github.com/ashiina/lambda-local/blob/develop/test/test.js#L213-L232

**Comment by efimk-lu** [comment]
Hi @gpotter2 ,

Trying to follow your example, but it just does not work well.

When running:
```nodejs
it("Timeout while running function, error not swallowed", () => {
		assert.throws(function() {
			const localHandler = (event, context) => {
				localHandler.called = true;
				setTimeout(() => {
					context.done(null, "Success");
				}, 300);
			};

			lambdaLocal.execute({
				event: {},
				lambdaFunc: { handler: localHandler },
				timeoutMs: 200
			}, utils.TimeoutError);
		});
	});
```

The test fails with 
```
AssertionError: expected [Function] to throw an error
    at Context.it (test/wrapper.js:318:10)
```

When removing `assert.throws`, e.g.
```nodejs
it("Timeout while running function, error not swallowed", done => {
		const localHandler = (event, context) => {
			localHandler.called = true;
			setTimeout(() => {
				context.done(null, "Success");
			}, 300);
		};

		lambdaLocal.execute({
			event: {},
			lambdaFunc: { handler: localHandler },
			timeoutMs: 200
		}, utils.TimeoutError);
	});
```

I'm getting 
```nodejs
TimeoutError: Task timed out after 0.20 seconds
    at Context.<anonymous> (node_modules/lambda-local/lib/context.js:103:15)
```

What am I missing?
