### ISSUE TITLE
uncaughtException readability

### ISSUE THREAD

**Issue by bootylactin** [ashiina/lambda-local#145]
First, thank you for this utility, it's been invaluable to our Lambda development!  Is there any way to clean up the formatting when an uncaughtException throws?  The stack trace below is extremely difficult to read in it's current state.

Thanks!

error: uncaughtException: Cannot read property 'throwAnError' of undefined date=Wed May 23 2018 13:34:13 GMT-0500 (Central Daylight Time), pid=111964, uid=null, gid=null, cwd=C:\Dev\eComm-Lambdas\ist-Shopping-services, execPath=C:\Program Fil
es\nodejs\node.exe, version=v6.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Program Files\nodejs\node_modules\lambda-local\bin\lambda-local, -l, index.js, -e, events/getMarginPrice.js, -t, 60], rss=72609792, heapTotal=65146880, heapUsed=3
8938800, external=18809825, loadavg=[0, 0, 0], uptime=172187.749799, trace=[column=18, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js, function=null, line=65, method=null, native=false, column=null, file=null, function=Arra
y.forEach, line=null, method=forEach, native=true, column=21, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js, function=getMarginAndNetPrice, line=63, method=null, native=false, column=6, file=C:\Dev\eComm-Lambdas\ist-Shoppi
ng-services\models\Product.js, function=Object.product_Resource, line=214, method=product_Resource, native=false, column=35, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\index.js, function=null, line=87, method=null, native=false, column=5
, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\local_modules\mongoose-connect.js, function=null, line=62, method=null, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js
, function=NativeConnection.emit, line=185, method=emit, native=false, column=12, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongoose\lib\connection.js, function=NativeConnection.set, line=114, method=set, native=false, colu
mn=24, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongoose\lib\connection.js, function=null, line=467, method=null, native=false, column=17, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\utils.js,
function=result, line=414, method=null, native=false, column=9, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\utils.js, function=executeCallback, line=406, method=null, native=false, column=5, file=C:\Dev\eComm-Lamb
das\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js, function=null, line=273, method=null, native=false, column=5, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js, function=connectCallba
ck, line=955, method=null, native=false, column=13, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js, function=null, line=825, method=null, native=false, column=7, file=internal/process/next_tick.js, fu
nction=_combinedTickCallback, line=67, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickDomainCallback, line=122, method=_tickDomainCallback, native=false], stack=[TypeError: Cannot read property
'throwAnError' of undefined,     at C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js:65:18,     at Array.forEach (native),     at getMarginAndNetPrice (C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js:63:21),     at Ob
ject.product_Resource (C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js:214:6),     at C:\Dev\eComm-Lambdas\ist-Shopping-services\index.js:87:35,     at NativeConnection.<anonymous> (C:\Dev\eComm-Lambdas\ist-Shopping-services\loca
l_modules\mongoose-connect.js:62:5),     at emitNone (events.js:86:13),     at NativeConnection.emit (events.js:185:7),     at NativeConnection.set (C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongoose\lib\connection.js:114:12),
   at C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongoose\lib\connection.js:467:24,     at result (C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\utils.js:414:17),     at executeCallback (C:\Dev\eComm-Lambdas
\ist-Shopping-services\node_modules\mongodb\lib\utils.js:406:9),     at C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js:273:5,     at connectCallback (C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules
\mongodb\lib\mongo_client.js:955:5),     at C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js:825:13,     at _combinedTickCallback (internal/process/next_tick.js:67:7),     at process._tickDomainCallback (int
ernal/process/next_tick.js:122:9)]

**Comment by gpotter2** [comment]
Hi !

Thanks for reporting, this should really be improved. I will have a look in the next days

I don’t really get at which point of lambda-local this is getting triggered, but will investigate

**Comment by bootylactin** [comment]
Gabriel,

Thanks for responding.  You can generate similar output to the above by causing any uncaught exception in your lambda code.  Adding the following inside your handler will suffice:

var e = throwAnError;

Best,

Jon

**Comment by gpotter2** [comment]
It seems that this was already fixed on the `develop` branch on github.

Could you check that ? There is no release yet, I will publish one soon if the fix is confirmed

**Comment by bootylactin** [comment]
This doesn't appear to be fixed, here's the output from the line of code I included above:

error: uncaughtException: throwAnError is not defined date=Fri May 25 2018 17:02:24 GMT-0500 (Central Daylight Time), pid=81148, uid=null, gid=null, cwd=C:\Dev\eComm-Lambdas\ist-Shopping-services, execPath=C:\Program Files\nodejs\node.exe, ve
rsion=v6.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Program Files\nodejs\node_modules\lambda-local\bin\lambda-local, -l, index.js, -e, events/getMarginPrice.js, -t, 60, --envfile, ../deploy-variables.sh], rss=79765504, heapTotal=6990643
2, heapUsed=43853976, external=18969656, loadavg=[0, 0, 0], uptime=357478.9971089, trace=[column=10, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js, function=getMarginAndNetPrice, line=61, method=null, native=false, column=
6, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js, function=Object.product_Resource, line=214, method=product_Resource, native=false, column=35, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\index.js, function=null, line=
87, method=null, native=false, column=5, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\local_modules\mongoose-connect.js, function=null, line=62, method=null, native=false, column=13, file=events.js, function=emitNone, line=86, method=null,
 native=false, column=7, file=events.js, function=NativeConnection.emit, line=185, method=emit, native=false, column=12, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongoose\lib\connection.js, function=NativeConnection.set, l
ine=114, method=set, native=false, column=24, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongoose\lib\connection.js, function=null, line=467, method=null, native=false, column=17, file=C:\Dev\eComm-Lambdas\ist-Shopping-servi
ces\node_modules\mongodb\lib\utils.js, function=result, line=414, method=null, native=false, column=9, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\utils.js, function=executeCallback, line=406, method=null, native=
false, column=5, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js, function=null, line=273, method=null, native=false, column=5, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\
mongo_client.js, function=connectCallback, line=955, method=null, native=false, column=13, file=C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js, function=null, line=825, method=null, native=false, column=7,
 file=internal/process/next_tick.js, function=_combinedTickCallback, line=67, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickDomainCallback, line=122, method=_tickDomainCallback, native=false],
stack=[ReferenceError: throwAnError is not defined,     at getMarginAndNetPrice (C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js:61:10),     at Object.product_Resource (C:\Dev\eComm-Lambdas\ist-Shopping-services\models\Product.js
:214:6),     at C:\Dev\eComm-Lambdas\ist-Shopping-services\index.js:87:35,     at NativeConnection.<anonymous> (C:\Dev\eComm-Lambdas\ist-Shopping-services\local_modules\mongoose-connect.js:62:5),     at emitNone (events.js:86:13),     at Nati
veConnection.emit (events.js:185:7),     at NativeConnection.set (C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongoose\lib\connection.js:114:12),     at C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongoose\lib\connecti
on.js:467:24,     at result (C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\utils.js:414:17),     at executeCallback (C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\utils.js:406:9),     at C:\Dev\eCom
m-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js:273:5,     at connectCallback (C:\Dev\eComm-Lambdas\ist-Shopping-services\node_modules\mongodb\lib\mongo_client.js:955:5),     at C:\Dev\eComm-Lambdas\ist-Shopping-servi
ces\node_modules\mongodb\lib\mongo_client.js:825:13,     at _combinedTickCallback (internal/process/next_tick.js:67:7),     at process._tickDomainCallback (internal/process/next_tick.js:122:9)]

What error output are you seeing on your side for uncaught exceptions?

**Comment by gpotter2** [comment]
I have published a new NPM version of lambda-local, could you please install it and retry ?

Here is what I get with such error:
![image](https://user-images.githubusercontent.com/10530980/40576365-50613010-60f5-11e8-9bd2-7cc22292df97.png)

**Comment by bootylactin** [comment]
@gpotter2 despite my best efforts, I am unable to reproduce the error output you are showing above with v1.4.8.  I've tried from PowerShell, the standard CMD, and Git Bash.  At this point I have to wonder if something in my code is interfering, or if perhaps the Node version is having some effect.  I've tried with both Node 6.10.0 and 8.4.0.

Can you send me your test lambda and event files so I can run them locally to see if that's the culprit?  Also, what version of Node are you running?

Thanks,

Jon

**Comment by gpotter2** [comment]
The test files are packed with this repository, in the test folder.

See the command I used (picture above) to trigger the line

I’m using Node 8.4.0, but I doubt the node version is responsible of it. You should check the lambda-local version :/

If you are in a shell, try install it with the `npm install -g lambda-local` or check the `node_modules` Folder for any outdated version.

This was fixed as above very recently, so an older version is surely the cause

**Comment by gpotter2** [comment]
Ok, if you find any issue that seems to be related with lambda-local, feel free to reopen :)

**Comment by bootylactin** [comment]
@gpotter2 is there any restriction to the length of the callstack that might be causing this issue?  I'm using the aws-sdk KMS.decrypt() function to parse encrypted environment variables, and I get the "bad" error output any time the callstack passes through this function.  When I bypass it, I get the "pretty" errors.

**Comment by gpotter2** [comment]
This is weird. `lambda-local` has no restriction of that kind.

We use a Winston logger to print the pretty test. 

- Maybe at some point `KMS.decrypt()` is messing with the console or Winston (the former is more likely).
- Maybe the way you are calling lambda-local is weird, and maybe the output of it is firstly processed into another program before being printed.

Have you an available small example of code (you can build it/fake the values/send it to me by email if required) that would reproduce the issue ?

Thanks

**Comment by bootylactin** [comment]
[errorTest.zip](https://github.com/ashiina/lambda-local/files/2055020/errorTest.zip)

Unzip, npm install, then

node_modules/.bin/lambda-local -l index.js -e test-event.js

You won't need to fill in your AWS KMS Key Id, simply calling the encrypt function with an empty string is enough to force the ugly error.

Thanks,

Jon

**Comment by gpotter2** [comment]
Error happens when the timeout is triggered: only then, does it show a different and ugly log message.

**Comment by bootylactin** [comment]
@gpotter2 when I run the above with -t 60 appended to the command, it throws the ugly error in less than a second.

Which test shows the catch?
