### ISSUE TITLE
Lambda async functions - unexpected token

### ISSUE THREAD

**Issue by tarasowski** [ashiina/lambda-local#158]
Hi guys,

thank you for working on lambda-local. Just tried to run a following function:

```js
module.exports.handler = async(event, context, callback) => {
    console.log(event)
    return 'Hello from Lambda'
}
```

```bash
$ lambda-local -l index.js -h handler -e examples/s3-put.js
warning Using both auth systems: aws_access_key/id and secret_access_token !
info: START RequestId: 995c192f-b25e-28c8-6579-0cee824da6f3
/home/ec2-user/environment/test/index.js:2
module.exports.handler = async(event, context, callback) => {
                              ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object._executeSync (/home/ec2-user/.nvm/versions/node/v6.14.3/lib/node_modules/lambda-local/lib/lambdalocal.js:157:26)
error: End - Error
error: ------
error: {
        "errorMessage": "Unexpected token (",
        "errorType": "SyntaxError",
        "stackTrace": [
                "ule.exports.handler = async(event, context, callback) => {",
                "",
                "",
                "taxError: Unexpected token (",
                "createScript (vm.js:56:10)",
                "Object.runInThisContext (vm.js:97:10)",
                "Module._compile (module.js:549:28)",
                "Object.Module._extensions..js (module.js:586:10)",
                "Module.load (module.js:494:32)",
                "tryModuleLoad (module.js:453:12)",
                "Function.Module._load (module.js:445:3)",
                "Module.require (module.js:504:17)",
                "require (internal/module.js:20:19)",
                "Object._executeSync (/home/ec2-user/.nvm/versions/node/v6.14.3/lib/node_modules/lambda-local/lib/lambdalocal.js:157:26)"
        ]
}
error: ------
error: Lambda failed in 18ms.
```

**Comment by gpotter2** [comment]
This is an issue with your function, you are wrongly declaring it (SyntaxError).

Have a look at https://stackoverflow.com/a/42964310/5459467

**Comment by tarasowski** [comment]
Yes, thank you! My node runtime was 6.xx on a new machine, haven't switched to 8.10.

**Comment by gpotter2** [comment]
Good ! Glad you fixed it
